dist: trusty

language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11
  
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
       - $HOME/.m2

# use operating systems.
os:
  - linux

script:
 - jdk_switcher use oraclejdk8
  - mvn test -f ./kotlin/pom.xml
  - mvn test -f ./java/pom.xml

after_success:
  - cd source
  - mvn clean test cobertura:cobertura coveralls:report
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=vicboma1_Kata-FizzBuzz
  
addons:
  sonarcloud:
    organization: "vicboma1" # the key of the org you chose at step #3
    token:
      secure: "a3ea36cb676926ab10d505b20b2a2cca43465461" # encrypted value of your token
